// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _ServerOperationsNC
{
    void addSong(String name, String artist, String path);

    void remove(String path);

    song[] findByTitle(String name);

    song[] findByArtist(String artist);

    song[] list();

    String start(String path);

    void play(String id);

    void stop(String id);

    boolean write(String name, int offset, byte[] data);
}
