// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface _ServerOperations
{
    void addSong(String name, String artist, String path, Ice.Current __current);

    void remove(String path, Ice.Current __current);

    song[] findByTitle(String name, Ice.Current __current);

    song[] findByArtist(String artist, Ice.Current __current);

    song[] list(Ice.Current __current);

    String start(String path, Ice.Current __current);

    void play(String id, Ice.Current __current);

    void stop(String id, Ice.Current __current);
}
