// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Player;

public interface MonitorPrx extends Ice.ObjectPrx
{
    public void report(String action, song s);

    public void report(String action, song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_report(String action, song s);

    public Ice.AsyncResult begin_report(String action, song s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_report(String action, song s, Ice.Callback __cb);

    public Ice.AsyncResult begin_report(String action, song s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_report(String action, song s, Callback_Monitor_report __cb);

    public Ice.AsyncResult begin_report(String action, song s, java.util.Map<String, String> __ctx, Callback_Monitor_report __cb);

    public void end_report(Ice.AsyncResult __result);
}
