// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `pocketSphinx.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package PocketSphinxIce;

public interface IPocketSphinxServer extends Ice.Object,
                                             _IPocketSphinxServerOperations, _IPocketSphinxServerOperationsNC
{
    public static final long serialVersionUID = -2066430442343256482L;
}
