// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `pocketSphinx.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package PocketSphinxIce;

public interface IPocketSphinxServerPrx extends Ice.ObjectPrx
{
    public String decode(short[] signal)
        throws Error;

    public String decode(short[] signal, java.util.Map<String, String> __ctx)
        throws Error;

    public Ice.AsyncResult begin_decode(short[] signal);

    public Ice.AsyncResult begin_decode(short[] signal, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_decode(short[] signal, Ice.Callback __cb);

    public Ice.AsyncResult begin_decode(short[] signal, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_decode(short[] signal, Callback_IPocketSphinxServer_decode __cb);

    public Ice.AsyncResult begin_decode(short[] signal, java.util.Map<String, String> __ctx, Callback_IPocketSphinxServer_decode __cb);

    public String end_decode(Ice.AsyncResult __result)
        throws Error;
}
